version: '3'
services:
    dvws-mongo:
        image: mongo:4.0.4
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 30s
            timeout: 5s
            retries: 10
            start_period: 10s
    dvws-mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: mysecretpassword
            MYSQL_DATABASE: dvws_sqldb
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root -pmysecretpassword
            interval: 30s
            timeout: 5s
            retries: 10
            start_period: 10s
    web:
        build: .
        ports:
        - "0.0.0.0:80:80"
        command: sh -c "node startup_script.js && npm start"
        environment:
            SQL_LOCAL_CONN_URL: dvws-mysql
            MONGO_LOCAL_CONN_URL: mongodb://dvws-mongo:27017/node-dvws
        depends_on:
            dvws-mongo:
                condition: service_healthy
            dvws-mysql:
                condition: service_healthy
