name: veracodescan
uses: veracode/veracode-uploadandscan-action
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    uses: actions/setup-java@v1
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: actions/checkout@v2
      with:
        java-version: 8
    - uses: actions/upload-artifact@v2
      with:
        path: '.'
    - uses: veracode/veracode-uploadandscan-action@master 
      with:
        filepath: '.'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        createsandbox: 'true'
        sandboxname: 'SANDBOXNAME'
        scantimeout: 15
        criticality: 'VeryHigh'
